spring.application.name=Study Sync

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}

# File Upload Configuration
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Stripe Payment Configuration
stripe.api.key.public=${STRIPE_PUBLIC_KEY}
stripe.api.key.secret=${STRIPE_SECRET_KEY}

# Ollama AI Configuration
spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.model=${OLLAMA_MODEL}

